### ISSUE TITLE
Should it be not in dependencies?

### ISSUE THREAD

**Issue by kono-paku** [wub/preact-cli-plugin-typescript#10]
Hi!
I have checked out how to install the package.
It looks like installing in devDependencies of package.json like below.

```
npm i preact-cli-plugin-typescript --save-dev
```

Does type check by using typescript does not occur in production?
I thought it ought to be supported in run-time as well.

**Comment by wub** [comment]
Hey @kono-paku, this plugin, and TypeScript, are only needed at build time - it gets turned into plain JavaScript, and any TypeScript-detectable errors will be caught when it builds.

I would recommend against compiling TypeScript in the browser!

**Comment by kono-paku** [comment]
@wub Thank you for answering the question! Although Typescript is needed for the build time, now I am wondering it is also required for the production build time.
Is there something I am misunderstanding?

**Comment by wub** [comment]
@kono-paku No problem! The "devDependencies" are also used when doing a "production" build. "dependencies" are only used for _runtime_, as in, things the browser/Node would use.

**Comment by kono-paku** [comment]
@wub Thanks Jarrod for fix my poor comprehension!
